import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {buildNavTree} from './src/nav/buildNav';

// Derive nav from docs/ once, at config-eval time. Drives the navbar dropdowns
// below and the mobile drawer (via customFields.navTree). Always matches the
// autogenerated sidebar.
const navTree = buildNavTree();
const docNavItems = navTree.nodes.map((n) =>
  n.kind === 'category'
    ? {
        type: 'dropdown' as const,
        label: n.label,
        position: 'left' as const,
        className: 'navbar-desktop-nav',
        items: n.items.map((i) => ({label: i.label, to: i.href})),
      }
    : {
        to: n.href,
        label: n.label,
        position: 'left' as const,
        className: 'navbar-desktop-nav',
      },
);

const config: Config = {
  title: 'Alto Motors Docs',
  tagline: 'Plain-language guides, wiring diagrams, and troubleshooting for Alto Motors systems.',
  favicon: 'img/favicon.ico',
  url: 'https://docs.altomotors.in',
  baseUrl: '/',
  organizationName: 'keshank',
  projectName: 'alto-docs',
  onBrokenLinks: 'warn',
  // Exposed to client components (the mobile drawer reads this).
  customFields: {navTree},
  future: {
    v4: true,
    faster: {
      swcJsLoader: true,
      swcJsMinimizer: true,
      swcHtmlMinimizer: true,
      lightningCssMinimizer: true,
      rspackBundler: false,
      rspackPersistentCache: false,
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // Mobile navbar search: expand-on-tap + close button (see src/clientModules)
  clientModules: [require.resolve('./src/clientModules/mobileSearchClose.ts')],

  // Local search — builds an offline search index at build time
  plugins: [
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexDocs: true,
        indexBlog: false,
        indexPages: false,
        language: ['en'],
        highlightSearchTermsOnTargetPage: true,
        searchBarShortcut: true,
        searchBarShortcutHint: true,
      },
    ],
  ],

  stylesheets: [
    {
      href: 'https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Source+Sans+3:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap',
      type: 'text/css',
    },
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Don't publish CLAUDE.md / AGENTS.md or any other agent rule files
          // that happen to live inside docs/ — they're authoring instructions,
          // not reader-facing pages.
          exclude: ['**/CLAUDE.md', '**/AGENTS.md', '**/.claude/**'],
          // No "Edit this page" link — suggestions go through the in-page
          // "Suggest an edit" form in the right-hand TOC instead.
          showLastUpdateTime: false,
          showLastUpdateAuthor: false,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    announcementBar: {
      id: 'al86-launch',
      content:
        'New: AL86 series datasheets & wiring diagrams are live. <a href="/docs/motors/bldc-al86" style="color:#D70000;font-weight:600;margin-left:6px;">Read what\'s new →</a>',
      backgroundColor: '#0d0d0d',
      textColor: '#ffffff',
      isCloseable: true,
    },
    colorMode: {
      defaultMode: 'light',
      // false = one click toggles; true causes the well-known "first click does nothing" bug
      respectPrefersColorScheme: false,
    },
    navbar: {
      hideOnScroll: false,
      logo: {
        alt: 'Alto Motors',
        src: 'img/alto-logo.svg',
        srcDark: 'img/alto-logo.svg',
        href: '/',
        width: 57,
        height: 32,
      },
      items: [
        // "/" divider + "DOCS" mono pill — matches design lockup: Alto / DOCS
        {
          type: 'html',
          position: 'left',
          className: 'navbar-lockup-item',
          value: '<span class="navbar-logo-sep">/</span><span class="navbar-docs-tag">DOCS</span>',
        },

        // ─── Desktop top-nav dropdowns (left). Hidden <=996px (.navbar-desktop-nav)
        //     — on tablet/mobile the same sections live in the hamburger drawer.
        //     Keep these in sync with src/data/drawerNav.ts. ───
        // ─── Auto-generated from docs/ (see buildNavTree). Mirrors the
        //     autogenerated sidebar exactly; new docs/folders appear here too. ───
        ...docNavItems,

        // Search slot — moved to the right (compact) so the left side holds the nav.
        {
          type: 'search',
          position: 'right',
          className: 'navbar-search-outer',
        },
        // altomotors.in link (right)
        {
          type: 'html',
          position: 'right',
          value: '<a href="https://altomotors.in" class="navbar__item navbar__link navbar-site-link" target="_blank" rel="noopener">altomotors.in ↗</a>',
        },
      ],
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: false,
      },
    },
    // Footer is rendered as a custom component on the homepage (src/pages/index.tsx).
    // For doc pages, keep a minimal copyright via Docusaurus's built-in footer.
    footer: {
      style: 'light',
      copyright: `© ${new Date().getFullYear()} Alto. All Rights Reserved.`,
    },
    prism: {
      // Syntax theme follows the site theme: light (github) in light mode,
      // dark (vsDark) in dark mode. The code surface/chrome is themed via the
      // --code-* CSS variables in custom.css.
      theme: prismThemes.github,
      darkTheme: prismThemes.vsDark,
      additionalLanguages: ['bash', 'json', 'ini'],
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
