import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebar: any .md/.mdx file dropped into docs/ shows up
 * automatically. Category labels, order, and collapsed state come from each
 * folder's _category_.json; item order within a category comes from each doc's
 * `sidebar_position` frontmatter (falling back to alphabetical).
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
