import fs from 'fs';
import path from 'path';

/**
 * Single source of truth for navigation.
 *
 * Scans docs/ and reproduces exactly what Docusaurus' autogenerated sidebar
 * does, so the navbar + mobile drawer always match it:
 *   - category label  ← folder's _category_.json "label", else the folder name
 *                        VERBATIM (Docusaurus does not prettify folder names)
 *   - ordering         ← _category_.json "position" / doc frontmatter
 *                        sidebar_position; unpositioned items sort last.
 *     Top-level categories and root docs are ordered together by position.
 *   - item label       ← doc frontmatter sidebar_label, else title, else filename
 *   - item "NEW" tag    ← doc frontmatter nav_tag
 *
 * Runs in Node only (config + customFields). Never import this into a browser
 * component — the drawer reads the result from siteConfig.customFields.navTree.
 */

const DOCS_DIR = path.join(process.cwd(), 'docs');
const ROUTE_BASE = '/docs';
const NO_POSITION = Number.MAX_SAFE_INTEGER;

// Files that live in docs/ but are NOT reader-facing pages. Kept in sync with
// the `exclude` list in docusaurus.config.ts → presets.classic.docs.exclude.
const NON_PAGE_FILES = new Set(['CLAUDE.md', 'AGENTS.md']);

// Mirror Docusaurus' own `draft` handling: draft pages are served in dev but
// excluded from the production build. So in production we must also drop them
// from the nav, or the navbar/drawer would link to a page that doesn't exist.
const EXCLUDE_DRAFTS = process.env.NODE_ENV === 'production';

export interface NavLeaf {
  label: string;
  href: string;
  tag?: string;
}
export interface NavCategoryNode {
  kind: 'category';
  label: string;
  collapsed: boolean;
  items: NavLeaf[];
}
export interface NavDocNode {
  kind: 'doc';
  label: string;
  href: string;
  tag?: string;
}
export type NavNode = NavCategoryNode | NavDocNode;
export interface NavTree {
  nodes: NavNode[];
}

interface Frontmatter {
  title?: string;
  sidebar_label?: string;
  sidebar_position?: number;
  id?: string;
  nav_tag?: string;
  draft?: boolean;
}

function parseFrontmatter(file: string): Frontmatter {
  const raw = fs.readFileSync(file, 'utf8');
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const fm: Frontmatter = {};
  if (!m) return fm;
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    const val = kv[2].trim().replace(/^["']|["']$/g, '');
    if (key === 'sidebar_position') fm.sidebar_position = Number(val);
    else if (key === 'title') fm.title = val;
    else if (key === 'sidebar_label') fm.sidebar_label = val;
    else if (key === 'id') fm.id = val;
    else if (key === 'nav_tag') fm.nav_tag = val;
    else if (key === 'draft') fm.draft = val === 'true';
  }
  return fm;
}

interface RankedLeaf extends NavLeaf {
  position: number;
  base: string;
}

function listDocs(absDir: string, relDir: string): RankedLeaf[] {
  const files = fs
    .readdirSync(absDir)
    .filter((f) => /\.mdx?$/.test(f) && !f.startsWith('_') && !NON_PAGE_FILES.has(f));
  const leaves = files
    .map((f) => ({f, fm: parseFrontmatter(path.join(absDir, f))}))
    // Drop drafts in production so the nav never links to an unbuilt page.
    .filter(({fm}) => !(EXCLUDE_DRAFTS && fm.draft))
    .map(({f, fm}) => {
    const base = f.replace(/\.mdx?$/, '');
    const seg = fm.id || base;
    const href = `${ROUTE_BASE}${relDir ? `/${relDir}` : ''}/${seg}`;
    const label = fm.sidebar_label || fm.title || base;
    return {
      label,
      href,
      tag: fm.nav_tag,
      position: fm.sidebar_position ?? NO_POSITION,
      base,
    };
  });
  leaves.sort((a, b) => a.position - b.position || a.base.localeCompare(b.base));
  return leaves;
}

function leaf({label, href, tag}: RankedLeaf): NavLeaf {
  return tag ? {label, href, tag} : {label, href};
}

interface RankedNode {
  node: NavNode;
  position: number;
  sortKey: string;
}

export function buildNavTree(): NavTree {
  const entries = fs.readdirSync(DOCS_DIR, {withFileTypes: true});
  const ranked: RankedNode[] = [];

  // Folders → categories
  for (const e of entries.filter((d) => d.isDirectory())) {
    const absDir = path.join(DOCS_DIR, e.name);
    let label = e.name; // Docusaurus uses the folder name verbatim by default
    let position = NO_POSITION;
    let collapsed = true;
    const catFile = path.join(absDir, '_category_.json');
    if (fs.existsSync(catFile)) {
      try {
        const j = JSON.parse(fs.readFileSync(catFile, 'utf8'));
        if (typeof j.label === 'string') label = j.label;
        if (typeof j.position === 'number') position = j.position;
        if (typeof j.collapsed === 'boolean') collapsed = j.collapsed;
      } catch {
        // malformed _category_.json — fall back to folder-name defaults
      }
    }
    const items = listDocs(absDir, e.name).map(leaf);
    if (items.length) {
      ranked.push({
        node: {kind: 'category', label, collapsed, items},
        position,
        sortKey: e.name,
      });
    }
  }

  // Root-level docs → standalone links
  for (const d of listDocs(DOCS_DIR, '')) {
    ranked.push({
      node: {kind: 'doc', label: d.label, href: d.href, ...(d.tag ? {tag: d.tag} : {})},
      position: d.position,
      sortKey: d.base,
    });
  }

  // Categories and root docs are ordered together by position (matches the
  // sidebar); unpositioned entries fall to the end.
  ranked.sort((a, b) => a.position - b.position || a.sortKey.localeCompare(b.sortKey));

  return {nodes: ranked.map((r) => r.node)};
}

export default buildNavTree;
